#!/usr/bin/env bash
# Produce an allowlist proposal from endpoints.json + an iptables drop-in.
# Usage: suggest_allowlist.sh [--min-count N] [--out DIR]
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(cd "$HERE/.." && pwd)"
LSA_ROOT="${LSA_ROOT:-$(cd "$SKILL_DIR/../.." && pwd)}"
. "$LSA_ROOT/lib/common.sh"

MIN_COUNT=2
OUT_OVERRIDE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --min-count) MIN_COUNT="$2"; shift 2;;
    --out)       OUT_OVERRIDE="$2"; shift 2;;
    -h|--help)   sed -n '1,3p' "$0"; exit 0;;
    *) die "unknown flag: $1";;
  esac
done

OUT="${OUT_OVERRIDE:-$(ensure_run_dir egress-control-audit)}"
mkdir -p "$OUT"
[ -s "$OUT/endpoints.json" ] || die "endpoints.json missing; run egress_check.sh first"

python3 - "$OUT" "$MIN_COUNT" <<'PY'
import json, os, sys, ipaddress
out, min_count = sys.argv[1], int(sys.argv[2])
eps = json.load(open(os.path.join(out,"endpoints.json")))

# Classify
kept = [e for e in eps if e["count"] >= min_count]
review = [e for e in eps if e["count"] < min_count]

# Group by (addr,port,proto)
by_endpoint = {}
for e in kept:
    k = (e["addr"], e["port"], e["proto"])
    by_endpoint[k] = by_endpoint.get(k, 0) + e["count"]

allow = []
for (addr, port, proto), c in sorted(by_endpoint.items()):
    allow.append({"addr": addr, "port": port, "proto": proto, "count": c})

# iptables drop-in
lines = []
lines.append("# Generated by suggest_allowlist.sh")
lines.append("# Apply with apply_egress_iptables.sh (dry-run by default)")
lines.append("*filter")
lines.append(":LSA_EGRESS - [0:0]")
lines.append("-A LSA_EGRESS -m state --state ESTABLISHED,RELATED -j ACCEPT")
lines.append("-A LSA_EGRESS -o lo -j ACCEPT")
# DNS to declared resolvers
try:
    resolvers = []
    for line in open("/etc/resolv.conf", errors="replace"):
        line = line.strip()
        if line.startswith("nameserver"):
            resolvers.append(line.split()[1])
    for r in resolvers:
        lines.append(f"-A LSA_EGRESS -p udp -d {r} --dport 53 -j ACCEPT")
        lines.append(f"-A LSA_EGRESS -p tcp -d {r} --dport 53 -j ACCEPT")
except Exception:
    pass
for e in allow:
    p = "tcp" if e["proto"].startswith("tcp") else ("udp" if e["proto"].startswith("udp") else e["proto"])
    a = e["addr"]
    try:
        ipaddress.ip_address(a)
    except ValueError:
        continue  # skip hostnames (iptables works on IPs)
    lines.append(f"-A LSA_EGRESS -p {p} -d {a} --dport {e['port']} -j ACCEPT  # count={e['count']}")
lines.append('-A LSA_EGRESS -j LOG --log-prefix "EGRESS-DROP " --log-level 4')
lines.append("-A LSA_EGRESS -j REJECT --reject-with icmp-port-unreachable")
lines.append("# Wire into OUTPUT:")
lines.append("# iptables -I OUTPUT 1 -j LSA_EGRESS")
lines.append("COMMIT")

with open(os.path.join(out,"egress.iptables.rules"),"w") as f:
    f.write("\n".join(lines) + "\n")

proposal = {
  "min_count": min_count,
  "allow": allow,
  "review_low_count": review[:200],
  "resolvers": [],
}
try:
    for line in open("/etc/resolv.conf", errors="replace"):
        line=line.strip()
        if line.startswith("nameserver"): proposal["resolvers"].append(line.split()[1])
except Exception: pass
open(os.path.join(out,"allowlist.suggested.json"),"w").write(json.dumps(proposal, indent=2))

# docker-network plan: by default, group containers that talk to each other into
# an internal network; do not infer external requirements automatically.
plan = {
  "note": "Heuristic only; review before applying. Each cluster gets its own user-defined bridge.",
  "clusters": []
}
open(os.path.join(out,"docker-network.plan.json"),"w").write(json.dumps(plan, indent=2))

# result.json for orchestrator
counts = {"allow_rules": len(allow), "review_items": len(review)}
data = {
  "module": "egress-control-audit",
  "status": "ok",
  "summary": f"{len(allow)} rule(s) proposed; {len(review)} low-count endpoints flagged for review",
  "counts": counts,
  "findings": [{"severity":"info","title":"egress-rule",
                "where": f'{e["addr"]}:{e["port"]}/{e["proto"]}',
                "note": f'count={e["count"]}'} for e in allow[:200]] +
              [{"severity":"low","title":"egress-rare-endpoint",
                "where": f'{e["addr"]}:{e["port"]}/{e["proto"]}',
                "note": f'count={e["count"]} (below min)'} for e in review[:50]],
}
open(os.path.join(out,"result.json"),"w").write(json.dumps(data, indent=2, ensure_ascii=False))
print(os.path.join(out,"result.json"))
PY

log_ok "allowlist proposal -> $OUT/allowlist.suggested.json"
echo "$OUT/result.json"
