#!/usr/bin/env python3
"""
AI Analysis Template Generator.
Generates prompts and data structures for AI-powered security analysis.
"""

def generate_ai_analysis_prompt(scan_data):
    """Generate a prompt for AI analysis of the scan results."""

    prompt = """# AI Security Analysis Request

Analyze the following security audit findings and provide:

1. **False Positive Validation**: Review each high/critical finding and determine if it's a true positive or false positive. Explain your reasoning.

2. **Risk Prioritization**: Score each finding 1-10 based on:
   - Exploitability in the current environment
   - Business impact if exploited
   - Likelihood of attack

3. **Attack Path Analysis**: Identify potential attack chains:
   - Can multiple findings be chained together?
   - What is the path from initial access to root/cluster-admin?

4. **Remediation Prioritization**: Order fixes by:
   - Which fixes block the most attack paths?
   - Which are quickest to implement with highest impact?

5. **Compliance Mapping**: Map findings to:
   - CIS Controls
   - NIST CSF
   - MITRE ATT&CK techniques

---

## Scan Summary

"""

    # Add summary data
    for module, counts in scan_data.get("summary", {}).items():
        prompt += f"**{module}**: {counts.get('status', 'unknown')} - "
        prompt += f"Critical: {counts.get('critical', 0)}, "
        prompt += f"High: {counts.get('high', 0)}, "
        prompt += f"Medium: {counts.get('medium', 0)}, "
        prompt += f"Low: {counts.get('low', 0)}\n"

    prompt += "\n---\n\n## Critical Findings\n\n"

    # Add critical findings
    for f in scan_data.get("privesc", {}).get("findings", []):
        if f.get("severity") == "critical":
            prompt += f"### {f.get('title', 'unknown')}\n"
            prompt += f"- **Location**: `{f.get('where', 'unknown')}`\n"
            prompt += f"- **Description**: {f.get('note', 'N/A')[:200]}\n\n"

    prompt += "\n---\n\n## High Findings\n\n"

    # Add high findings (limited)
    count = 0
    for f in scan_data.get("privesc", {}).get("findings", []):
        if f.get("severity") == "high" and count < 20:
            prompt += f"### {f.get('title', 'unknown')}\n"
            prompt += f"- **Location**: `{f.get('where', 'unknown')[:100]}`\n"
            prompt += f"- **Description**: {f.get('note', 'N/A')[:150]}\n\n"
            count += 1

    # Add kernel CVEs
    kernel_cves = scan_data.get("kernel_cves", [])
    if kernel_cves:
        prompt += "\n---\n\n## Kernel Vulnerabilities\n\n"
        for cve in kernel_cves:
            prompt += f"- **{cve['cve']}** ({cve['name']}): {cve['status']}\n"

    # Add sensitive findings summary
    sensitive_raw = scan_data.get("sensitive_raw", [])
    if sensitive_raw:
        prompt += f"\n---\n\n## Sensitive Information\n\n"
        prompt += f"Total secrets found: {len(sensitive_raw)}\n"

        # Count by type
        from collections import Counter
        by_type = Counter(f.get("RuleID", f.get("title", "unknown")) for f in sensitive_raw)
        prompt += "\nBy type:\n"
        for t, c in by_type.most_common(10):
            prompt += f"- {t}: {c}\n"

    prompt += """

---

## Analysis Request

Please provide your analysis in the following format:

### 1. False Positive Analysis
[List each finding and your FP/TP determination with reasoning]

### 2. Risk Scores
[Finding → Score (1-10) → Reasoning]

### 3. Attack Paths
[Diagram or description of potential attack chains]

### 4. Remediation Priority
[Ordered list with estimated effort and impact]

### 5. Compliance Mapping
[CIS Control → NIST CSF → MITRE ATT&CK]
"""

    return prompt


def generate_ai_analysis_report(ai_response, output_dir):
    """Save AI analysis response to report file."""
    from pathlib import Path

    output_path = Path(output_dir) / "ai-analysis-report.md"

    content = f"""# AI Security Analysis Report

**Generated by**: Claude AI
**Analysis Type**: Deep Security Analysis

---

{ai_response}
"""

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)

    return output_path


def get_analysis_context(scan_dir, scan_data):
    """Get context data for AI analysis including raw evidence."""
    from pathlib import Path

    context = {
        "summary": scan_data.get("summary", {}),
        "critical_findings": [],
        "high_findings": [],
        "kernel_cves": scan_data.get("kernel_cves", []),
        "linpeas_evidence": "",
        "cdk_evidence": "",
        "sensitive_samples": []
    }

    # Get critical and high findings
    for f in scan_data.get("privesc", {}).get("findings", []):
        if f.get("severity") == "critical":
            context["critical_findings"].append(f)
        elif f.get("severity") == "high":
            context["high_findings"].append(f)

    # Get LinPEAS evidence for critical areas
    scan_dir = Path(scan_dir)
    linpeas_file = scan_dir / "privesc-escape-check/linpeas_raw.txt"
    if linpeas_file.exists():
        content = linpeas_file.read_text(encoding='utf-8', errors='replace')
        # Extract key sections
        for keyword in ["docker.sock", "writable cron", "CVE-2026", "privileged"]:
            idx = content.lower().find(keyword)
            if idx > 0:
                start = max(0, idx - 100)
                end = min(len(content), idx + 500)
                context["linpeas_evidence"] += content[start:end] + "\n\n"

    # Get sample sensitive findings
    sensitive_raw = scan_data.get("sensitive_raw", [])
    for f in sensitive_raw[:10]:
        context["sensitive_samples"].append({
            "type": f.get("RuleID", f.get("title", "")),
            "file": f.get("File", f.get("where", ""))[:100],
            "entropy": f.get("Entropy", 0)
        })

    return context
